repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.3
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: 'v0.6.13'
    hooks:
    - id: cmake-format
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        description: Format files with clang-format
        entry: clang-format
        language: system
        files: ^(src\/nle|include\/nle|win\/rl|sys\/unix\/nle).*\.(c|cc|cxx|cpp|cu|h|hpp|hxx|cuh|proto)$
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
