[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | src
  | win/rl/nethack_rl
)/
'''

[tool.isort]
force_single_line = true
profile = "black"
skip_glob = "**/__init__.py"

[tool.ruff]
# See https://docs.astral.sh/ruff/rules/.
extend-exclude = [
  "third_party",
]
exclude = ["win/rl/nle"]
[tool.ruff.lint]
ignore = [
    "B008",
    "B905",
    "C901",
    "E501",
    "E731",
]
select = [
    "B",
    "B9",
    "C",
    "E",
    "F",
    "W",
    "R",
]
[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # unused-import.
