# This workflow tests publishing artefacts to TestPyPI.
# It is triggered when a release is created with the
# "Set as a pre-release" option is selected.

name: Test Publish
on:
  release:
    types: [prereleased]

jobs:
  test_deploy:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/nle #TODO Update to TestPyPI URL
    steps:
      - uses: actions/checkout@v4
      - name: Get sdist artifact # Get sdist artifact from the test_sdist job
        uses: actions/download-artifact@v4
        with:
          name: python-sdist
          path: dist
      - name: Get wheels artifacts # Get wheels artifacts from the build_wheels job
        uses: actions/download-artifact@v4
        with:
          name: python-wheels
          path: dist
      - name: Report dist contents
        run: |
          pwd
          ls -R
          ls -al .
          ls -R dist/
          ls -al dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
